### ISSUE TITLE
Symbol not  found

### ISSUE THREAD

**Issue by ajalexei** [jupyter-xeus/xeus-python#584]
I am experiencing the following problem with xeux-python kernel in Jupyter (Apple M1): xpython kernel fails to start.
Manually running xpython produces the following message (identical to the message in Jupyter logs):
```
dyld[xxxx]: Symbol not found: __ZN4xeus23make_xserver_shell_mainERNS_8xcontextERKNS_14xconfigurationEN8nlohmann6detail15error_handler_tE
  Referenced from: <BFEB1A78-751B-3410-A578-D004B1CAAE71> /opt/mambaforge/bin/xpython
  Expected in:     <C15F7F38-D49B-3C1E-AB7D-0BC6FA1ECC67> /opt/mambaforge/lib/libxeus-zmq.1.0.0.dylib
Abort trap
```

Mambaforge: python 3.10.9  
```
xeus                                 3.0.5              hffc8910_1    conda-forge
xeus-python                     0.15.7            py310h2887b22_0    conda-forge
xeus-python-shell            0.5.0              pyhd8ed1ab_0    conda-forge
xeus-python-shell-raw     0.5.0              pyhd8ed1ab_0    conda-forge
xeus-zmq                        1.0.2               h54398fd_2    conda-forge
jupyter_client            8.1.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.0           py310hbe9552e_0    conda-forge
jupyter_events            0.6.3              pyhd8ed1ab_0    conda-forge
jupyter_server            2.5.0              pyhd8ed1ab_0    conda-forge
jupyter_server_fileid     0.8.0              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyter_server_ydoc       0.8.0              pyhd8ed1ab_0    conda-forge
jupyter_ydoc              0.2.3              pyhd8ed1ab_0    conda-forge
jupyterlab                3.6.2              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.20.0             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.6              pyhd8ed1ab_0    conda-forge
```

**Comment by JohanMabille** [comment]
Thanks for reporting, there was some constraint relaxing in `xeus-python` dependencies recently, leading to ugrating `nlohmann_json` to an ABI backward incompatible version. Rebuilding xeus-python should fix it.

**Comment by ajalexei** [comment]
ok, thanks for the prompt reply.

Just in case -- the problem is also present for x86_64:
`/opt/mambaforge/bin/xpython: symbol lookup error: /opt/mambaforge/bin/../lib/libxeus-python.so.0: undefined symbol: _ZN4xeus14xdebugger_base20process_request_implERKN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS1_14adl_serializerES4_IhSaIhEEEESG_`

**Comment by ajalexei** [comment]
> Thanks for reporting, there was some constraint relaxing in `xeus-python` dependencies recently, leading to ugrating `nlohmann_json` to an ABI backward incompatible version.
> 
> `xeus-python` 0.15.8 (currently building) should work.

Unfortunately it still doesn't: I updated to the latest version
`- xeus-python          0.15.7  py310h2887b22_0     conda-forge                    
  + xeus-python          0.15.8  py310h2887b22_0     conda-forge/osx-arm64`
but the error still persists:
`Symbol not found: __ZN4xeus23make_xserver_shell_mainERNS_8xcontextERKNS_14xconfigurationEN8nlohmann6detail15error_handler_tE
22613   │   Referenced from: <979E5460-BE6F-397F-8BB7-56CF60FB5EF6> /opt/mambaforge/bin/xpython
22614   │   Expected in:     <C15F7F38-D49B-3C1E-AB7D-0BC6FA1ECC67> /opt/mambaforge/lib/libxeus-zmq.1.0.0.dylib`

**Comment by JohanMabille** [comment]
Looks like you have an incompatible version of xeus-zmq, can you force the upgrade to `xeus-zmq 1.0.2` ?

**Comment by ajalexei** [comment]
> Looks like you have an incompatible version of xeus-zmq, can you force the upgrade to `xeus-zmq 1.0.2` ?

The version is 1.0.2 already:
`xeus-zmq                  1.0.2                h54398fd_2    conda-forge`

**Comment by JohanMabille** [comment]
Ha my bad, the constraint on nlohmann_json was not properly relaxed when building xeus-python 0.15.8, sorry for that.
https://github.com/conda-forge/xeus-python-feedstock/pull/166 should fix it for good.

**Comment by ajalexei** [comment]
Indeed, all good now. Thanks for a prompt fix!

**Comment by ajalexei** [comment]
The issue reappeared on macos(am64), linux (amd64, arm64) with xpython 0.17.4 and xeus > 5.2.0, xeus-zmq 3.1.0, h227b3ab_2 (when installed via micromamba):

macos (arm64):
"""
dyld[55090]: Symbol not found: __ZN4xeus23make_xserver_shell_mainERNS_8xcontextERKNS_14xconfigurationEN8nlohmann16json_abi_v3_11_36detail15error_handler_tE
  Referenced from: <EC3AD309-D723-3461-9502-590724994FAA> /opt/micromamba/envs/313/bin/xpython
  Expected in:     <E1F8D42A-E063-35C9-A568-F6FC94D4AD5D> /opt/micromamba/envs/313/lib/libxeus-zmq.6.0.1.dylib
The process was killed by SIGABRT: Abort trap: 6
"""

Similar error messages are present on linux systems.

The problem disappears if I downgrade to xeus=5.2.0 (again via micromamba)

**Comment by anutosh491** [comment]
Could you please try using nlohmann_json `3.12.0`

**Comment by ajalexei** [comment]
Just installing that version of conda package does not resolve the issue.
